# [START runtime]
runtime: nodejs8
handlers:
- url: /
  static_files: dist/health-check-client/index.html
  upload: dist/health-check-client/index.html
- url: /
  static_dir: dist/health-check-client
# [END runtime]