image: node:chakracore-10.13

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - cd client;npm install 

stages:
  - test
  - build
 
job 1:
  stage: test
  script: cd client;node_modules/.bin/ng test

job 2:
  stage: test
  script: cd client;node_modules/.bin/ng e2e

release_job:
  stage: build
  script: node_modules/.bin/ng build --prod --aot
  artifacts:
    name: "project-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  only:
    - tags
