image: weltn24/up-docker-node-chrome-headless

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - test
  - build
 
run unit tests:
  stage: test
  before_script:
    - cd client
    - npm install
  script: node_modules/.bin/ng test

run e2e tests:
  stage: test
  before_script:
    - cd client
    - npm install
  script: node_modules/.bin/ng e2e

release_job:
  stage: build
  script: node_modules/.bin/ng build --prod --aot
  artifacts:
    name: "project-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  only:
    - tags
