image: node:chakracore-10.13

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - test
  - build

install dependencies:
  stage: test
  script: cd client && npm install --silent
  
check status:
  stage: test
  script: dir
  
unit tests:
  stage: test
  script: node_modules/.bin/ng test

e2e tests:
  stage: test
  script: node_modules/.bin/ng e2e

release_job:
  stage: build
  script: node_modules/.bin/ng build --prod --aot
  artifacts:
    name: "project-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  only:
    - tags
